name: wizard_player_media
description: "跨平台视频播放器抽象库，为 WizardPlayer 提供统一的播放器接口"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  amis_flutter_utils:
    git:
      url: https://gitee.com/AmisKwok/amis_flutter_utils.git
      ref: main

  # GetX 状态管理
  get: ^4.7.3

  # 视频播放核心：media_kit（Windows/Linux/macOS/Android/iOS/Web 全平台）
  media_kit: ^1.2.6 # Primary package.
  media_kit_video: ^2.0.1 # For video rendering.
  media_kit_libs_video: ^1.0.7 # Native video dependencies.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
